#!/usr/bin/env bash
# AiTOS development environment setup (macOS + Linux)
#
# Usage:
#   ./scripts/install_devenv.sh              # install deps, write env.rc, verify build
#   ./scripts/install_devenv.sh --skip-install   # only write env.rc + verify
#   ./scripts/install_devenv.sh --no-verify      # install deps + write env.rc
#   ./scripts/install_devenv.sh --force-env      # overwrite existing env.rc
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SKIP_INSTALL=0
NO_VERIFY=0
FORCE_ENV=0

for arg in "$@"; do
	case "$arg" in
		--skip-install) SKIP_INSTALL=1 ;;
		--no-verify) NO_VERIFY=1 ;;
		--force-env) FORCE_ENV=1 ;;
		-h|--help)
			sed -n '2,8p' "$0"
			exit 0
			;;
		*)
			echo "Unknown option: $arg" >&2
			exit 1
			;;
	esac
done

log()  { printf '==> %s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

have() { command -v "$1" >/dev/null 2>&1; }

gcc_major() {
	local cc="$1"
	local ver major

	ver="$("$cc" -dumpversion 2>/dev/null)" || return 1
	major="${ver%%.*}"
	echo "$major"
}

check_gcc_version() {
	local cc="$1"
	local major

	major="$(gcc_major "$cc")" || die "cannot get version from $cc"
	if [ "$major" -lt 13 ] 2>/dev/null; then
		die "AiTOS requires GCC >= 13 (found $("$cc" -dumpversion) via $cc)"
	fi
}

select_linux_gcc() {
	local major

	if have gcc; then
		major="$(gcc_major gcc)" || major=0
		if [ "$major" -ge 13 ] 2>/dev/null; then
			echo gcc
			return 0
		fi
	fi
	if have gcc-13; then
		major="$(gcc_major gcc-13)" || major=0
		if [ "$major" -ge 13 ] 2>/dev/null; then
			echo gcc-13
			return 0
		fi
	fi
	die "GCC >= 13 required; install gcc-13 or upgrade system gcc"
}

make_cc() {
	local cc=""

	if [ -f env.rc ]; then
		cc="$(grep -E '^CC\s*:=' env.rc | sed 's/^CC\s*:=\s*//' | tr -d ' \t' || true)"
	fi
	echo "${cc:-gcc}"
}

detect_os() {
	case "$(uname -s)" in
		Darwin) echo macos ;;
		Linux)  echo linux ;;
		*) die "unsupported OS: $(uname -s) (only macOS and Linux)" ;;
	esac
}

detect_linux_pm() {
	if have apt-get; then
		echo apt
	elif have dnf; then
		echo dnf
	elif have yum; then
		echo yum
	elif have pacman; then
		echo pacman
	elif have apk; then
		echo apk
	else
		die "no supported package manager found (apt/dnf/yum/pacman/apk)"
	fi
}

run_as_root() {
	if [ "$(id -u)" -eq 0 ]; then
		"$@"
	elif have sudo; then
		sudo "$@"
	else
		die "root privileges required; re-run with sudo or install packages manually"
	fi
}

install_macos() {
	if ! have brew; then
		die "Homebrew not found. Install from https://brew.sh then re-run this script."
	fi

	log "Installing macOS dependencies via Homebrew..."
	brew install x86_64-elf-gcc x86_64-elf-binutils nasm qemu gdb tmux grub xorriso
}

install_linux() {
	local pm major
	pm="$(detect_linux_pm)"

	log "Installing Linux dependencies via ${pm}..."

	case "$pm" in
		apt)
			run_as_root apt-get update -qq
			run_as_root apt-get install -y \
				build-essential nasm gcc gdb \
				qemu-system-x86 tmux \
				grub-pc-bin grub-common xorriso
			if have gcc; then
				major="$(gcc_major gcc)" || major=0
				if [ "$major" -lt 13 ] 2>/dev/null; then
					if apt-cache show gcc-13 >/dev/null 2>&1; then
						log "System gcc < 13; installing gcc-13..."
						run_as_root apt-get install -y gcc-13
					fi
				fi
			fi
			;;
		dnf)
			run_as_root dnf install -y \
				make gcc nasm gdb \
				qemu-system-x86_64 tmux
			;;
		yum)
			run_as_root yum install -y \
				make gcc nasm gdb \
				qemu-system-x86_64 tmux
			;;
		pacman)
			run_as_root pacman -Sy --noconfirm \
				base-devel nasm gcc gdb \
				qemu-system-x86_64 tmux
			;;
		apk)
			run_as_root apk add \
				build-base nasm gcc gdb \
				qemu-system-x86_64 tmux
			;;
	esac
}

write_env_rc_macos() {
	cat > env.rc <<'EOF'
# Generated by scripts/install_devenv.sh (macOS)
# AiTOS requires GCC >= 13. Apple Clang cannot build bare-metal ELF kernels.

CC := x86_64-elf-gcc
LD := x86_64-elf-ld
OBJCOPY := x86_64-elf-objcopy

# Optional shell overrides for scripts/debug*.sh
# export QEMU=qemu-system-x86_64
# export GDB=gdb
# export GDB_PORT=1234
EOF
}

write_env_rc_linux() {
	local cc

	cc="$(select_linux_gcc)"
	cat > env.rc <<EOF
# Generated by scripts/install_devenv.sh (Linux)
# AiTOS requires GCC >= 13.

CC := ${cc}
LD := ld
OBJCOPY := objcopy

# Optional shell overrides for scripts/debug*.sh
# export QEMU=qemu-system-x86_64
# export GDB=gdb
# export GDB_PORT=1234
EOF
}

configure_env_rc() {
	if [ -f env.rc ] && [ "$FORCE_ENV" -eq 0 ]; then
		log "env.rc already exists (use --force-env to overwrite)"
		return
	fi

	case "$(detect_os)" in
		macos) write_env_rc_macos ;;
		linux) write_env_rc_linux ;;
	esac
	log "Wrote env.rc"
}

require_tool() {
	local name="$1"
	shift
	if ! have "$name"; then
		die "missing required tool: $name ($*)"
	fi
}

verify_tools() {
	local cc

	log "Checking required tools..."

	require_tool nasm "NASM assembler"
	require_tool make "GNU Make"
	require_tool dd "disk image utility"

	case "$(detect_os)" in
		macos)
			require_tool x86_64-elf-gcc "brew install x86_64-elf-gcc"
			check_gcc_version x86_64-elf-gcc
			require_tool x86_64-elf-ld "brew install x86_64-elf-binutils"
			require_tool x86_64-elf-objcopy "brew install x86_64-elf-binutils"
			;;
		linux)
			cc="$(make_cc)"
			require_tool "$cc" "GCC >= 13 (build-essential / gcc-13)"
			check_gcc_version "$cc"
			require_tool ld "binutils"
			require_tool objcopy "binutils"
			;;
	esac

	if have qemu-system-x86_64; then
		:
	elif have qemu-system-i386; then
		warn "qemu-system-x86_64 not found; qemu-system-i386 is present (Makefile defaults to x86_64)"
	else
		die "missing QEMU (qemu-system-x86_64)"
	fi

	if ! have gdb; then
		warn "gdb not found; debugging targets will not work until gdb is installed"
	fi

	if ! have tmux; then
		warn "tmux not found; make debug-tmux will fall back to make debug"
	fi
}

verify_build() {
	log "Verifying build (make)..."
	make clean-all
	make
	log "Build OK: bin/hd60M.img"
}

print_notes() {
	cat <<'EOF'

Development environment is ready.

Quick start:
  make              # build disk image
  make run-qemu     # run in QEMU (terminal output)
  make debug        # GDB debugging (type 'c' to continue)

On macOS, if gdb reports permission errors, codesign it once:
  https://sourceware.org/gdb/wiki/PermissionsDarwin

EOF
}

OS="$(detect_os)"

if [ "$SKIP_INSTALL" -eq 0 ]; then
	case "$OS" in
		macos) install_macos ;;
		linux) install_linux ;;
	esac
else
	log "Skipping package installation (--skip-install)"
fi

configure_env_rc
verify_tools

if [ "$NO_VERIFY" -eq 0 ]; then
	verify_build
else
	log "Skipping build verification (--no-verify)"
fi

log "Installing git hooks"
bash "$ROOT/scripts/install_git_hooks.sh"

print_notes
